project_id = "osvicgbgrmyogazdbllj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_anonymous_sign_ins = false

[edge_functions]
enabled = true
port = 54323

[functions.workout-templates]
verify_jwt = false

[functions.ai-coach-create-workout]
verify_jwt = true

[functions.nutrition-ai-chat]
verify_jwt = false

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions.admin-update-plan]
verify_jwt = true

[functions.ai-coach]  
verify_jwt = true

[functions.auth-email-config]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.create-premium-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.workouts-api-proxy]
verify_jwt = true