// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osvicgbgrmyogazdbllj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zdmljZ2Jncm15b2dhemRibGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NzU3MzQsImV4cCI6MjA3MzA1MTczNH0.xtMgUn0_T0KX4jPMW8eIZ_JeLZ5du0185NiUgRpuBFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});